//Login
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

//Get notes
GET http://localhost:4000/notes/:id

###

//Post notes
POST http://localhost:4000/notes
Content-Type: application/json

{
    "text": "text"
}

###

//Delete notes
DELETE http://localhost:4000/notes/2
Content-Type: application/json

###

//Update notes
PUT http://localhost:4000/notes/1
Content-Type: application/json

{
    "text": "ÄNDRAT"
}